"""short and long description can be nullable

Revision ID: e039f3143aa3
Revises: 220396514242
Create Date: 2023-06-30 11:45:43.546260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e039f3143aa3'
down_revision = '220396514242'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='user', column_name='short_description',nullable=True)
    op.alter_column(table_name='user', column_name='long_bio',nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='user', column_name='short_description',nullable=False)
    op.alter_column(table_name='user', column_name='long_bio',nullable=False)
    # ### end Alembic commands ###
